# =========================================================
# APPLICATION
# =========================================================
spring.application.name=stock_sale_mgnt_v1


# =========================================================
# SERVER
# =========================================================
server.port=8080


# =========================================================
# POSTGRESQL DATABASE
# =========================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/stock_sale_mgnt_db
spring.datasource.username=postgres
spring.datasource.password=jaysyatdb
spring.datasource.driver-class-name=org.postgresql.Driver


# =========================================================
# JPA / HIBERNATE
# =========================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# =========================================================
# DATABASE INITIALIZATION
# =========================================================
spring.sql.init.mode=never

# =========================================================
# LOGGING
# =========================================================
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# =========================================================
# JWT
# =========================================================
app.jwt.secret=7270c58070519e21a3ff0e518d04d406ee19d40940fd036fa0a8843c7a383b82
app.jwt.expiration=86400000